***************************************************************************************************** 
* WARNING: The 2021 software stack is not available on the 'genoa' partition.
Please use the 2022 * 
* software stack. * 
* * 
* If you have any question, please contact us via
http://servicedesk.surfsara.nl. * 
***************************************************************************************************** 
To connect to the notebook type the following command from your local terminal:
ssh -J qiahan@int5-pub.snellius.surf.nl qiahan@fcn47.local.snellius.surf.nl -L 5199:localhost:5199

After connection is established in your local browser go to the address:
http://localhost:5199
[I 2023-09-05 10:00:39.487 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-09-05 10:00:40.341 ServerApp] Package dask_labextension took 0.8538s to import
[W 2023-09-05 10:00:40.341 ServerApp] A `_jupyter_server_extension_points` function was not found in dask_labextension. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-05 10:00:41.131 ServerApp] Package ipyparallel took 0.7892s to import
[W 2023-09-05 10:00:41.131 ServerApp] A `_jupyter_server_extension_points` function was not found in ipyparallel. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-05 10:00:41.137 ServerApp] Package jupyter_server_fileid took 0.0056s to import
[I 2023-09-05 10:00:41.140 ServerApp] Package jupyter_server_mathjax took 0.0033s to import
[I 2023-09-05 10:00:41.141 ServerApp] Package jupyter_server_proxy took 0.0000s to import
[I 2023-09-05 10:00:41.158 ServerApp] Package jupyter_server_terminals took 0.0165s to import
[I 2023-09-05 10:00:41.233 ServerApp] Package jupyter_server_ydoc took 0.0748s to import
[I 2023-09-05 10:00:41.284 ServerApp] Package jupyterlab_git took 0.0510s to import
[I 2023-09-05 10:00:41.285 ServerApp] Package nbclassic took 0.0000s to import
[W 2023-09-05 10:00:41.290 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-05 10:00:41.290 ServerApp] Package nbdime took 0.0000s to import
[I 2023-09-05 10:00:41.290 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-09-05 10:00:41.290 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-05 10:00:41.292 ServerApp] dask_labextension | extension was successfully linked.
[I 2023-09-05 10:00:41.293 ServerApp] ipyparallel | extension was successfully linked.
[I 2023-09-05 10:00:41.299 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-09-05 10:00:41.307 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2023-09-05 10:00:41.307 ServerApp] jupyter_server_proxy | extension was successfully linked.
[I 2023-09-05 10:00:41.313 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-09-05 10:00:41.319 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2023-09-05 10:00:41.371 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-09-05 10:00:41.372 ServerApp] jupyterlab_git | extension was successfully linked.
[I 2023-09-05 10:00:41.379 ServerApp] nbclassic | extension was successfully linked.
[I 2023-09-05 10:00:41.380 ServerApp] nbdime | extension was successfully linked.
[I 2023-09-05 10:00:41.395 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-09-05 10:00:41.575 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-09-05 10:00:41.578 ServerApp] dask_labextension | extension was successfully loaded.
[I 2023-09-05 10:00:41.583 ServerApp] Loading IPython parallel extension
[I 2023-09-05 10:00:41.583 ServerApp] ipyparallel | extension was successfully loaded.
[I 2023-09-05 10:00:41.583 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-09-05 10:00:41.584 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /gpfs/work2/0/ttse0619/qianqian
[I 2023-09-05 10:00:41.584 FileIdExtension] ArbitraryFileIdManager : Configured database path: /gpfs/home2/qiahan/.local/share/jupyter/file_id_manager.db
[I 2023-09-05 10:00:41.585 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-09-05 10:00:41.585 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-09-05 10:00:41.586 FileIdExtension] Attached event listeners.
[I 2023-09-05 10:00:41.587 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-09-05 10:00:41.587 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2023-09-05 10:00:41.604 ServerApp] jupyter_server_proxy | extension was successfully loaded.
[I 2023-09-05 10:00:41.605 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-09-05 10:00:41.605 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2023-09-05 10:00:41.620 LabApp] JupyterLab extension loaded from /home/qiahan/.conda/envs/mamba/envs/emulator/lib/python3.9/site-packages/jupyterlab
[I 2023-09-05 10:00:41.620 LabApp] JupyterLab application directory is /gpfs/home2/qiahan/.conda/envs/mamba/envs/emulator/share/jupyter/lab
[I 2023-09-05 10:00:41.624 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-09-05 10:00:41.629 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2023-09-05 10:00:41.640 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-09-05 10:00:41.796 ServerApp] nbdime | extension was successfully loaded.
[I 2023-09-05 10:00:41.797 ServerApp] Serving notebooks from local directory: /gpfs/work2/0/ttse0619/qianqian
[I 2023-09-05 10:00:41.797 ServerApp] Jupyter Server 2.5.0 is running at:
[I 2023-09-05 10:00:41.797 ServerApp] http://localhost:5199/lab?token=9ff363edb3d6a3899eb07e2e2a8897db2a92def15a2bd887
[I 2023-09-05 10:00:41.797 ServerApp]     http://127.0.0.1:5199/lab?token=9ff363edb3d6a3899eb07e2e2a8897db2a92def15a2bd887
[I 2023-09-05 10:00:41.797 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-09-05 10:00:41.803 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///gpfs/home2/qiahan/.local/share/jupyter/runtime/jpserver-1854525-open.html
    Or copy and paste one of these URLs:
        http://localhost:5199/lab?token=9ff363edb3d6a3899eb07e2e2a8897db2a92def15a2bd887
        http://127.0.0.1:5199/lab?token=9ff363edb3d6a3899eb07e2e2a8897db2a92def15a2bd887
[I 2023-09-05 10:01:30.230 LabApp] Generating new user for token-authenticated request: a9976d06e08e42b487ef415566e894c2
[I 2023-09-05 10:01:33.776 LabApp] Build is up to date
[I 2023-09-05 10:01:40.218 ServerApp] Kernel started: 6ebe678b-85b3-4aea-82b5-b76a6662e3ba
[I 2023-09-05 10:01:40.978 ServerApp] Connecting to kernel 6ebe678b-85b3-4aea-82b5-b76a6662e3ba.
[I 2023-09-05 10:01:40.980 ServerApp] Connecting to kernel 6ebe678b-85b3-4aea-82b5-b76a6662e3ba.
[I 2023-09-05 10:01:41.014 ServerApp] Connecting to kernel 6ebe678b-85b3-4aea-82b5-b76a6662e3ba.
[I 2023-09-05 10:03:01.167 ServerApp] Kernel started: 38f332be-8437-4d7c-a967-2cff3436fe42
[I 2023-09-05 10:03:01.802 ServerApp] Connecting to kernel 38f332be-8437-4d7c-a967-2cff3436fe42.
[I 2023-09-05 10:03:39.888 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_2000steps.ipynb
[I 2023-09-05 10:09:00.887 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 10:15:54.586 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_2000steps.ipynb
[I 2023-09-05 10:16:09.893 ServerApp] Trying to establish websocket connection to ws://localhost:41563/status/ws
[I 2023-09-05 10:16:09.895 ServerApp] Websocket connection established to ws://localhost:41563/status/ws
[I 2023-09-05 10:16:31.778 ServerApp] Kernel restarted: 38f332be-8437-4d7c-a967-2cff3436fe42
[I 2023-09-05 10:16:31.794 ServerApp] Starting buffering for 38f332be-8437-4d7c-a967-2cff3436fe42:9d67f591-8a3f-4173-8f0e-ef2ab2c7c18c
[I 2023-09-05 10:16:31.858 ServerApp] Connecting to kernel 38f332be-8437-4d7c-a967-2cff3436fe42.
[I 2023-09-05 10:16:31.858 ServerApp] Restoring connection for 38f332be-8437-4d7c-a967-2cff3436fe42:9d67f591-8a3f-4173-8f0e-ef2ab2c7c18c
[I 2023-09-05 10:16:41.563 ServerApp] Kernel restarted: 6ebe678b-85b3-4aea-82b5-b76a6662e3ba
[I 2023-09-05 10:16:41.589 ServerApp] Connecting to kernel 6ebe678b-85b3-4aea-82b5-b76a6662e3ba.
[I 2023-09-05 10:17:02.806 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[W 2023-09-05 10:17:41.635 ServerApp] Notebook global_data_Qianqian/Emulator/2daskParallel/2read10kminput-halfhourly-0628_1year.ipynb is not trusted
[I 2023-09-05 10:17:44.482 ServerApp] Kernel started: cc797fbb-5bdf-448e-a52a-1ffc4a589171
[I 2023-09-05 10:17:45.074 ServerApp] Connecting to kernel cc797fbb-5bdf-448e-a52a-1ffc4a589171.
[I 2023-09-05 10:17:45.076 ServerApp] Connecting to kernel cc797fbb-5bdf-448e-a52a-1ffc4a589171.
[I 2023-09-05 10:17:45.103 ServerApp] Connecting to kernel cc797fbb-5bdf-448e-a52a-1ffc4a589171.
[I 2023-09-05 10:18:02.889 ServerApp] Trying to establish websocket connection to ws://localhost:8787/status/ws
[I 2023-09-05 10:18:02.891 ServerApp] Websocket connection established to ws://localhost:8787/status/ws
[I 2023-09-05 10:19:03.085 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 10:21:03.522 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[W 2023-09-05 10:24:34.089 ServerApp] Replacing stale connection: cc797fbb-5bdf-448e-a52a-1ffc4a589171:bf8e24dd-8fb3-4632-a82f-cf2625e3ead6
[I 2023-09-05 10:24:34.091 ServerApp] Connecting to kernel cc797fbb-5bdf-448e-a52a-1ffc4a589171.
[W 2023-09-05 10:24:34.095 ServerApp] 
[W 2023-09-05 10:24:34.096 ServerApp] 
[W 2023-09-05 10:24:34.097 ServerApp] 
[W 2023-09-05 10:24:34.098 ServerApp] 
[W 2023-09-05 10:24:34.100 ServerApp] 
[W 2023-09-05 10:24:34.101 ServerApp] 
[W 2023-09-05 10:24:34.974 ServerApp] Replacing stale connection: 6ebe678b-85b3-4aea-82b5-b76a6662e3ba:ebfef350-0ad4-4296-9921-b5c273f80ed5
[I 2023-09-05 10:24:34.975 ServerApp] Connecting to kernel 6ebe678b-85b3-4aea-82b5-b76a6662e3ba.
[W 2023-09-05 10:24:34.980 ServerApp] 
[W 2023-09-05 10:24:34.980 ServerApp] 
[W 2023-09-05 10:24:34.981 ServerApp] 
[W 2023-09-05 10:24:34.982 ServerApp] 
[W 2023-09-05 10:24:35.197 ServerApp] Replacing stale connection: 6ebe678b-85b3-4aea-82b5-b76a6662e3ba:9635112c-18d5-4acc-9bfe-25cf02b2a0b4
[I 2023-09-05 10:24:35.198 ServerApp] Connecting to kernel 6ebe678b-85b3-4aea-82b5-b76a6662e3ba.
[W 2023-09-05 10:24:35.202 ServerApp] 
[W 2023-09-05 10:24:35.202 ServerApp] 
[W 2023-09-05 10:24:35.203 ServerApp] 
[W 2023-09-05 10:24:35.203 ServerApp] 
[W 2023-09-05 10:24:35.204 ServerApp] 
[W 2023-09-05 10:24:35.204 ServerApp] 
[W 2023-09-05 10:24:35.204 ServerApp] 
[W 2023-09-05 10:24:35.205 ServerApp] 
[W 2023-09-05 10:24:35.207 ServerApp] 
[W 2023-09-05 10:24:35.207 ServerApp] 
[W 2023-09-05 10:24:35.208 ServerApp] 
[W 2023-09-05 10:24:35.208 ServerApp] 
[W 2023-09-05 10:24:35.650 ServerApp] Replacing stale connection: 38f332be-8437-4d7c-a967-2cff3436fe42:9d67f591-8a3f-4173-8f0e-ef2ab2c7c18c
[I 2023-09-05 10:24:35.651 ServerApp] Connecting to kernel 38f332be-8437-4d7c-a967-2cff3436fe42.
[W 2023-09-05 10:24:35.657 ServerApp] 
[W 2023-09-05 10:24:35.657 ServerApp] 
[W 2023-09-05 10:24:35.659 ServerApp] 
[W 2023-09-05 10:24:35.659 ServerApp] 
[W 2023-09-05 10:24:35.661 ServerApp] 
[W 2023-09-05 10:24:35.662 ServerApp] 
[W 2023-09-05 10:24:35.713 ServerApp] 
[W 2023-09-05 10:24:35.717 ServerApp] 
[W 2023-09-05 10:24:35.718 ServerApp] 
[W 2023-09-05 10:24:35.719 ServerApp] 
[W 2023-09-05 10:24:35.720 ServerApp] 
[W 2023-09-05 10:24:35.720 ServerApp] 
[W 2023-09-05 10:24:35.721 ServerApp] 
[W 2023-09-05 10:24:35.722 ServerApp] 
[W 2023-09-05 10:24:35.723 ServerApp] 
[W 2023-09-05 10:24:35.724 ServerApp] 
[W 2023-09-05 10:24:35.725 ServerApp] 
[W 2023-09-05 10:24:35.726 ServerApp] 
[W 2023-09-05 10:24:35.727 ServerApp] 
[W 2023-09-05 10:24:35.727 ServerApp] 
[W 2023-09-05 10:24:35.766 ServerApp] 
[W 2023-09-05 10:24:35.766 ServerApp] 
[W 2023-09-05 10:24:35.772 ServerApp] 
[W 2023-09-05 10:24:35.773 ServerApp] 
[W 2023-09-05 10:24:35.776 ServerApp] 
[W 2023-09-05 10:24:35.777 ServerApp] 
[W 2023-09-05 10:24:35.829 ServerApp] 
[W 2023-09-05 10:24:35.830 ServerApp] 
[I 2023-09-05 10:24:38.546 LabApp] Generating new user for token-authenticated request: a6f4a0bfbbe44fa4b467ff0c95dfea43
[W 2023-09-05 10:24:38.631 ServerApp] 
[W 2023-09-05 10:24:38.631 ServerApp] 
[W 2023-09-05 10:24:38.632 ServerApp] 
[W 2023-09-05 10:24:38.632 ServerApp] 
[W 2023-09-05 10:24:38.633 ServerApp] 
[W 2023-09-05 10:24:38.633 ServerApp] 
[W 2023-09-05 10:24:38.634 ServerApp] 
[W 2023-09-05 10:24:38.635 ServerApp] 
[W 2023-09-05 10:24:38.635 ServerApp] 
[W 2023-09-05 10:24:38.636 ServerApp] 
[W 2023-09-05 10:24:38.636 ServerApp] 
[W 2023-09-05 10:24:38.637 ServerApp] 
[W 2023-09-05 10:24:38.637 ServerApp] 
[W 2023-09-05 10:24:38.638 ServerApp] 
[W 2023-09-05 10:24:38.639 ServerApp] 
[W 2023-09-05 10:24:38.639 ServerApp] 
[W 2023-09-05 10:24:38.640 ServerApp] 
[W 2023-09-05 10:24:38.640 ServerApp] 
[W 2023-09-05 10:24:38.641 ServerApp] 
[W 2023-09-05 10:24:38.641 ServerApp] 
[W 2023-09-05 10:24:38.642 ServerApp] 
[W 2023-09-05 10:24:38.642 ServerApp] 
[W 2023-09-05 10:24:38.648 ServerApp] 
[W 2023-09-05 10:24:38.648 ServerApp] 
[W 2023-09-05 10:24:38.649 ServerApp] 
[W 2023-09-05 10:24:38.649 ServerApp] 
[I 2023-09-05 10:24:41.917 LabApp] Build is up to date
[I 2023-09-05 10:24:43.865 ServerApp] Connecting to kernel 6ebe678b-85b3-4aea-82b5-b76a6662e3ba.
[I 2023-09-05 10:24:43.885 ServerApp] Connecting to kernel 38f332be-8437-4d7c-a967-2cff3436fe42.
[I 2023-09-05 10:24:54.428 ServerApp] Kernel restarted: 38f332be-8437-4d7c-a967-2cff3436fe42
[I 2023-09-05 10:24:54.456 ServerApp] Connecting to kernel 38f332be-8437-4d7c-a967-2cff3436fe42.
[I 2023-09-05 10:25:04.761 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 10:25:15.717 ServerApp] Starting buffering for cc797fbb-5bdf-448e-a52a-1ffc4a589171:bf8e24dd-8fb3-4632-a82f-cf2625e3ead6
[I 2023-09-05 10:26:47.695 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 10:27:31.868 ServerApp] Trying to establish websocket connection to ws://localhost:8787/status/ws
[I 2023-09-05 10:27:31.870 ServerApp] Websocket connection established to ws://localhost:8787/status/ws
[I 2023-09-05 10:28:48.806 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
2023-09-05 10:29:23,513 - ServerApp - ERROR - Uncaught exception 
Traceback (most recent call last):
  File "/home/qiahan/.local/lib/python3.9/site-packages/tornado/websocket.py", line 630, in _run_callback
    result = callback(*args, **kwargs)
  File "/home/qiahan/.local/lib/python3.9/site-packages/tornado/websocket.py", line 1519, in on_message
    return self._on_message(message)
  File "/home/qiahan/.local/lib/python3.9/site-packages/tornado/websocket.py", line 1525, in _on_message
    self._on_message_callback(message)
  File "/home/qiahan/.conda/envs/mamba/envs/emulator/lib/python3.9/site-packages/jupyter_server_proxy/handlers.py", line 475, in message_cb
    self.write_message(message, binary=isinstance(message, bytes))
  File "/home/qiahan/.local/lib/python3.9/site-packages/tornado/websocket.py", line 331, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
[I 2023-09-05 10:29:23.779 ServerApp] Trying to establish websocket connection to ws://localhost:8787/status/ws
[I 2023-09-05 10:29:23.781 ServerApp] Websocket connection established to ws://localhost:8787/status/ws
[I 2023-09-05 10:29:32.271 ServerApp] Trying to establish websocket connection to ws://localhost:8787/workers/ws
[I 2023-09-05 10:29:32.273 ServerApp] Websocket connection established to ws://localhost:8787/workers/ws
[I 2023-09-05 10:30:45.764 ServerApp] Trying to establish websocket connection to ws://localhost:8787/workers/ws
[I 2023-09-05 10:30:45.766 ServerApp] Websocket connection established to ws://localhost:8787/workers/ws
[I 2023-09-05 10:30:49.494 ServerApp] Trying to establish websocket connection to ws://localhost:8787/status/ws
[I 2023-09-05 10:30:49.496 ServerApp] Websocket connection established to ws://localhost:8787/status/ws
[I 2023-09-05 10:30:49.781 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 10:32:50.440 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 10:34:23.556 ServerApp] Trying to establish websocket connection to ws://localhost:8787/status/ws
[I 2023-09-05 10:34:23.674 ServerApp] Websocket connection established to ws://localhost:8787/status/ws
2023-09-05 10:39:51,961 - distributed.utils_perf - WARNING - full garbage collections took 49% CPU time recently (threshold: 10%)
2023-09-05 10:39:52,723 - distributed.utils_perf - WARNING - full garbage collections took 50% CPU time recently (threshold: 10%)
2023-09-05 10:39:54,771 - distributed.utils_perf - WARNING - full garbage collections took 50% CPU time recently (threshold: 10%)
2023-09-05 10:39:56,980 - distributed.utils_perf - WARNING - full garbage collections took 50% CPU time recently (threshold: 10%)
2023-09-05 10:39:59,765 - distributed.utils_perf - WARNING - full garbage collections took 50% CPU time recently (threshold: 10%)
2023-09-05 10:40:02,856 - distributed.utils_perf - WARNING - full garbage collections took 49% CPU time recently (threshold: 10%)
2023-09-05 10:40:07,660 - distributed.utils_perf - WARNING - full garbage collections took 49% CPU time recently (threshold: 10%)
2023-09-05 10:40:10,711 - distributed.utils_perf - WARNING - full garbage collections took 49% CPU time recently (threshold: 10%)
2023-09-05 10:40:11,509 - distributed.utils_perf - WARNING - full garbage collections took 49% CPU time recently (threshold: 10%)
2023-09-05 10:40:13,847 - distributed.utils_perf - WARNING - full garbage collections took 49% CPU time recently (threshold: 10%)
2023-09-05 10:40:16,208 - distributed.utils_perf - WARNING - full garbage collections took 49% CPU time recently (threshold: 10%)
2023-09-05 10:40:18,728 - distributed.utils_perf - WARNING - full garbage collections took 49% CPU time recently (threshold: 10%)
2023-09-05 10:40:21,870 - distributed.utils_perf - WARNING - full garbage collections took 49% CPU time recently (threshold: 10%)
2023-09-05 10:40:26,247 - distributed.utils_perf - WARNING - full garbage collections took 48% CPU time recently (threshold: 10%)
2023-09-05 10:40:31,268 - distributed.utils_perf - WARNING - full garbage collections took 48% CPU time recently (threshold: 10%)
2023-09-05 10:40:36,904 - distributed.utils_perf - WARNING - full garbage collections took 47% CPU time recently (threshold: 10%)
2023-09-05 10:40:37,836 - distributed.utils_perf - WARNING - full garbage collections took 34% CPU time recently (threshold: 10%)
2023-09-05 10:40:41,606 - distributed.utils_perf - WARNING - full garbage collections took 48% CPU time recently (threshold: 10%)
2023-09-05 10:40:43,252 - distributed.utils_perf - WARNING - full garbage collections took 36% CPU time recently (threshold: 10%)
2023-09-05 10:40:44,383 - distributed.utils_perf - WARNING - full garbage collections took 34% CPU time recently (threshold: 10%)
2023-09-05 10:40:47,173 - distributed.utils_perf - WARNING - full garbage collections took 48% CPU time recently (threshold: 10%)
2023-09-05 10:40:50,931 - distributed.utils_perf - WARNING - full garbage collections took 35% CPU time recently (threshold: 10%)
2023-09-05 10:40:52,563 - distributed.utils_perf - WARNING - full garbage collections took 36% CPU time recently (threshold: 10%)
2023-09-05 10:40:53,479 - distributed.utils_perf - WARNING - full garbage collections took 47% CPU time recently (threshold: 10%)
2023-09-05 10:40:58,205 - distributed.utils_perf - WARNING - full garbage collections took 36% CPU time recently (threshold: 10%)
2023-09-05 10:41:00,130 - distributed.utils_perf - WARNING - full garbage collections took 47% CPU time recently (threshold: 10%)
2023-09-05 10:41:01,372 - distributed.utils_perf - WARNING - full garbage collections took 37% CPU time recently (threshold: 10%)
2023-09-05 10:41:06,966 - distributed.utils_perf - WARNING - full garbage collections took 37% CPU time recently (threshold: 10%)
2023-09-05 10:41:07,247 - distributed.utils_perf - WARNING - full garbage collections took 47% CPU time recently (threshold: 10%)
2023-09-05 10:41:11,308 - distributed.utils_perf - WARNING - full garbage collections took 37% CPU time recently (threshold: 10%)
2023-09-05 10:41:14,769 - distributed.utils_perf - WARNING - full garbage collections took 46% CPU time recently (threshold: 10%)
2023-09-05 10:41:16,485 - distributed.utils_perf - WARNING - full garbage collections took 38% CPU time recently (threshold: 10%)
2023-09-05 10:41:21,736 - distributed.utils_perf - WARNING - full garbage collections took 37% CPU time recently (threshold: 10%)
2023-09-05 10:41:23,172 - distributed.utils_perf - WARNING - full garbage collections took 46% CPU time recently (threshold: 10%)
2023-09-05 10:41:25,548 - distributed.utils_perf - WARNING - full garbage collections took 38% CPU time recently (threshold: 10%)
2023-09-05 10:41:31,965 - distributed.utils_perf - WARNING - full garbage collections took 46% CPU time recently (threshold: 10%)
2023-09-05 10:41:32,870 - distributed.utils_perf - WARNING - full garbage collections took 36% CPU time recently (threshold: 10%)
2023-09-05 10:41:35,683 - distributed.utils_perf - WARNING - full garbage collections took 39% CPU time recently (threshold: 10%)
2023-09-05 10:41:41,865 - distributed.utils_perf - WARNING - full garbage collections took 45% CPU time recently (threshold: 10%)
2023-09-05 10:41:46,483 - distributed.utils_perf - WARNING - full garbage collections took 36% CPU time recently (threshold: 10%)
2023-09-05 10:41:46,832 - distributed.utils_perf - WARNING - full garbage collections took 40% CPU time recently (threshold: 10%)
2023-09-05 10:41:51,786 - distributed.utils_perf - WARNING - full garbage collections took 46% CPU time recently (threshold: 10%)
2023-09-05 10:41:59,166 - distributed.utils_perf - WARNING - full garbage collections took 40% CPU time recently (threshold: 10%)
2023-09-05 10:42:00,355 - distributed.utils_perf - WARNING - full garbage collections took 36% CPU time recently (threshold: 10%)
2023-09-05 10:42:03,581 - distributed.utils_perf - WARNING - full garbage collections took 46% CPU time recently (threshold: 10%)
2023-09-05 10:42:12,898 - distributed.utils_perf - WARNING - full garbage collections took 40% CPU time recently (threshold: 10%)
2023-09-05 10:42:15,200 - distributed.utils_perf - WARNING - full garbage collections took 36% CPU time recently (threshold: 10%)
2023-09-05 10:42:15,762 - distributed.utils_perf - WARNING - full garbage collections took 46% CPU time recently (threshold: 10%)
2023-09-05 10:42:28,345 - distributed.utils_perf - WARNING - full garbage collections took 40% CPU time recently (threshold: 10%)
2023-09-05 10:42:29,365 - distributed.utils_perf - WARNING - full garbage collections took 47% CPU time recently (threshold: 10%)
2023-09-05 10:42:44,700 - distributed.utils_perf - WARNING - full garbage collections took 40% CPU time recently (threshold: 10%)
2023-09-05 10:49:44,618 - distributed.utils_perf - WARNING - full garbage collections took 61% CPU time recently (threshold: 10%)
[I 2023-09-05 10:49:44.814 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
2023-09-05 10:50:30,848 - distributed.utils_perf - WARNING - full garbage collections took 63% CPU time recently (threshold: 10%)
2023-09-05 10:51:29,767 - distributed.utils_perf - WARNING - full garbage collections took 66% CPU time recently (threshold: 10%)
[I 2023-09-05 10:51:45.845 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
2023-09-05 10:52:28,062 - distributed.utils_perf - WARNING - full garbage collections took 66% CPU time recently (threshold: 10%)
2023-09-05 10:53:29,683 - distributed.utils_perf - WARNING - full garbage collections took 66% CPU time recently (threshold: 10%)
[I 2023-09-05 10:53:46.782 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
2023-09-05 10:54:22,890 - distributed.utils_perf - WARNING - full garbage collections took 65% CPU time recently (threshold: 10%)
2023-09-05 10:55:40,556 - distributed.utils_perf - WARNING - full garbage collections took 65% CPU time recently (threshold: 10%)
[I 2023-09-05 10:55:47.849 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
2023-09-05 10:57:08,367 - distributed.utils_perf - WARNING - full garbage collections took 65% CPU time recently (threshold: 10%)
[I 2023-09-05 10:57:48.802 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
2023-09-05 10:58:07,945 - distributed.utils_perf - WARNING - full garbage collections took 65% CPU time recently (threshold: 10%)
2023-09-05 10:58:15,605 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 40.77 GiB -- Worker memory limit: 60.00 GiB
2023-09-05 10:58:26,015 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 41.68 GiB -- Worker memory limit: 60.00 GiB
2023-09-05 10:59:31,100 - distributed.utils_perf - WARNING - full garbage collections took 65% CPU time recently (threshold: 10%)
2023-09-05 10:59:33,243 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 41.82 GiB -- Worker memory limit: 60.00 GiB
2023-09-05 10:59:43,605 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 41.60 GiB -- Worker memory limit: 60.00 GiB
[I 2023-09-05 10:59:49.767 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
2023-09-05 10:59:54,190 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 42.04 GiB -- Worker memory limit: 60.00 GiB
2023-09-05 11:00:06,510 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 42.07 GiB -- Worker memory limit: 60.00 GiB
2023-09-05 11:00:17,008 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 42.26 GiB -- Worker memory limit: 60.00 GiB
2023-09-05 11:00:27,466 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 42.29 GiB -- Worker memory limit: 60.00 GiB
2023-09-05 11:00:37,611 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 42.15 GiB -- Worker memory limit: 60.00 GiB
2023-09-05 11:00:48,908 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 42.27 GiB -- Worker memory limit: 60.00 GiB
2023-09-05 11:01:00,745 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 42.63 GiB -- Worker memory limit: 60.00 GiB
[I 2023-09-05 11:01:50.061 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:02:04.059 ServerApp] Kernel interrupted: 38f332be-8437-4d7c-a967-2cff3436fe42
[I 2023-09-05 11:02:06.005 ServerApp] Kernel interrupted: 38f332be-8437-4d7c-a967-2cff3436fe42
Process Dask Worker process (from Nanny):
Process Dask Worker process (from Nanny):
Process Dask Worker process (from Nanny):
2023-09-05 11:02:06,006 - distributed.nanny - ERROR - Worker process died unexpectedly
2023-09-05 11:02:06,006 - distributed.nanny - ERROR - Worker process died unexpectedly
2023-09-05 11:02:06,006 - distributed.nanny - ERROR - Worker process died unexpectedly
Traceback (most recent call last):
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/distributed/nanny.py", line 999, in _run
    asyncio.run(run())
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/distributed/process.py", line 202, in _run
    target(*args, **kwargs)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/distributed/nanny.py", line 999, in _run
    asyncio.run(run())
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/contextlib.py", line 532, in __exit__
    raise exc_details[1]
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/contextlib.py", line 517, in __exit__
    if cb(*exc_details):
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/contextlib.py", line 405, in _exit_wrapper
    callback(*args, **kwds)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/threading.py", line 1064, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/threading.py", line 1080, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/distributed/nanny.py", line 999, in _run
    asyncio.run(run())
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/distributed/process.py", line 202, in _run
    target(*args, **kwargs)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/distributed/nanny.py", line 999, in _run
    asyncio.run(run())
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/contextlib.py", line 532, in __exit__
    raise exc_details[1]
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/contextlib.py", line 517, in __exit__
    if cb(*exc_details):
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/contextlib.py", line 405, in _exit_wrapper
    callback(*args, **kwds)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/threading.py", line 1064, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/threading.py", line 1080, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/distributed/nanny.py", line 999, in _run
    asyncio.run(run())
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/asyncio/base_events.py", line 1869, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/distributed/process.py", line 202, in _run
    target(*args, **kwargs)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/distributed/nanny.py", line 999, in _run
    asyncio.run(run())
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/contextlib.py", line 532, in __exit__
    raise exc_details[1]
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/contextlib.py", line 517, in __exit__
    if cb(*exc_details):
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/contextlib.py", line 405, in _exit_wrapper
    callback(*args, **kwds)
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/threading.py", line 1064, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/home/qiahan/.conda/envs/firstEnv/lib/python3.9/threading.py", line 1080, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
[I 2023-09-05 11:02:11.649 ServerApp] Kernel restarted: 38f332be-8437-4d7c-a967-2cff3436fe42
[I 2023-09-05 11:02:11.659 ServerApp] Starting buffering for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 11:02:11.667 ServerApp] Connecting to kernel 38f332be-8437-4d7c-a967-2cff3436fe42.
[I 2023-09-05 11:02:11.667 ServerApp] Restoring connection for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 11:03:50.470 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:05:50.771 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:15:51.113 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:17:51.471 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:19:51.822 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:21:52.105 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:23:52.414 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:27:45.788 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:28:01.757 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:30:02.067 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:32:02.498 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:34:02.781 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:36:03.089 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:38:03.367 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:40:03.727 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:42:04.035 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:43:46.968 ServerApp] Trying to establish websocket connection to ws://localhost:8787/status/ws
[I 2023-09-05 11:43:46.971 ServerApp] Websocket connection established to ws://localhost:8787/status/ws
[I 2023-09-05 11:44:04.419 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:46:04.840 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:48:05.178 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:50:05.489 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:52:05.881 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 11:54:06.230 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
[I 2023-09-05 11:56:06.777 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
[I 2023-09-05 11:58:07.797 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 12:00:08.112 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
[I 2023-09-05 12:02:06.658 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 12:04:39.289 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 12:05:22.453 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 12:05:42.858 ServerApp] Starting buffering for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 12:05:42.860 ServerApp] Starting buffering for 6ebe678b-85b3-4aea-82b5-b76a6662e3ba:d6092e58-3c7b-43c2-8a85-2ab5a8240005
[I 2023-09-05 12:05:43.937 ServerApp] Connecting to kernel 38f332be-8437-4d7c-a967-2cff3436fe42.
[I 2023-09-05 12:05:43.937 ServerApp] Restoring connection for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 12:05:43.957 ServerApp] Connecting to kernel 6ebe678b-85b3-4aea-82b5-b76a6662e3ba.
[I 2023-09-05 12:05:43.957 ServerApp] Restoring connection for 6ebe678b-85b3-4aea-82b5-b76a6662e3ba:d6092e58-3c7b-43c2-8a85-2ab5a8240005
[I 2023-09-05 12:05:44.106 ServerApp] Starting buffering for 6ebe678b-85b3-4aea-82b5-b76a6662e3ba:d6092e58-3c7b-43c2-8a85-2ab5a8240005
[I 2023-09-05 12:05:44.107 ServerApp] Starting buffering for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 12:53:26.723 ServerApp] Connecting to kernel 38f332be-8437-4d7c-a967-2cff3436fe42.
[I 2023-09-05 12:53:26.735 ServerApp] Restoring connection for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 12:53:47.698 ServerApp] Connecting to kernel 6ebe678b-85b3-4aea-82b5-b76a6662e3ba.
[I 2023-09-05 12:53:47.698 ServerApp] Restoring connection for 6ebe678b-85b3-4aea-82b5-b76a6662e3ba:d6092e58-3c7b-43c2-8a85-2ab5a8240005
[I 2023-09-05 12:57:25.797 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 12:59:26.054 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:01:26.259 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:03:26.498 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:05:26.763 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:07:27.061 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:09:27.309 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:11:27.562 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:13:27.830 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:15:28.031 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:17:28.263 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:19:09.284 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:21:09.529 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:23:10.828 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:25:11.044 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:27:11.293 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:29:11.567 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:35:11.825 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:37:12.102 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:37:55.411 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
2023-09-05 13:38:09,325 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-6443d21720efab6da162a51ce7ef1b3c', 0, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x14cd5d6228b0>, <function predictFlux at 0x14cd5d20ba60>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         [            nan,             nan,             nan, ...,
                      nan,             nan,             nan],
         ...,
         [-6.94444461e-05, -6.94444461e-05, -6.94444461e-05, ...,
          -6.94444461e-05, -6.94444461e-05, -6.94444461e-05],
         [-6.94444461e-05, -6.94444461e-05, -6.94444461e-05, ...,
          -6.94444461e-05, -6.94444461e-05, -6.94444461e-05],
         [-6.94444461e-05, -6.94444461e-05, -6.94444461e-05, ...,
          -6.94444461e-05
kwargs:    {}
Exception: "ValueError('all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 10404000 and the array at index 8 has size 2601')"

2023-09-05 13:38:09,339 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-6443d21720efab6da162a51ce7ef1b3c', 1, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x1483ee09aa60>, <function predictFlux at 0x1483ee0e1af0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [4.00766937e+02, 4.01652374e+02, 4.02215820e+02, ...,
          4.34975830e+02, 4.35458893e+02, 4.35941803e+02],
         [4.01893890e+02, 4.02698761e+02, 4.03342773e+02, ...,
          4.37309998e+02, 4.37712646e+02, 4.38275970e+02],
         [4.02940277e+02, 4.03745148e+02, 4.04469574e+02, ...,
          4.39805420e+02, 4.40127350e+02, 4.40529846e+02]]
kwargs:    {}
Exception: "ValueError('all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 10404000 and the array at index 8 has size 2601')"

/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
2023-09-05 13:38:09,461 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-6443d21720efab6da162a51ce7ef1b3c', 4, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x1483ee087af0>, <function predictFlux at 0x1483ee087c10>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [6.49429860e+01, 6.48050675e+01, 6.49085402e+01, ...,
          6.65975723e+01, 6.84245138e+01, 7.02514563e+01],
         [6.70111756e+01, 6.69767380e+01, 6.70802088e+01, ...,
          6.95620794e+01, 7.18370829e+01, 7.40432682e+01],
         [6.88381271e+01, 6.89415979e+01, 6.90449972e+01, ...,
          7.18715982e+01, 7.43190317e+01, 7.68354177e+01]]
kwargs:    {}
Exception: "ValueError('all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2601000 and the array at index 8 has size 2601')"

2023-09-05 13:38:09,500 - distributed.worker - WARNING - Compute Failed
Key:       ('predictFlux-<this-array>-predictFlux-6443d21720efab6da162a51ce7ef1b3c', 3, 0, 0, 0)
Function:  execute_task
args:      ((<built-in function getitem>, (<function map_blocks.<locals>._wrapper at 0x15282df88040>, <function predictFlux at 0x1528187cd1f0>, [(<class 'xarray.core.dataset.Dataset'>, (<class 'dict'>, [[<this-array>, (('variable', 'time', 'latitude', 'longitude'), array([[[[           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         [           nan,            nan,            nan, ...,
                     nan,            nan,            nan],
         ...,
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          0.00000000e+00, 0.00000000e+00, 0.00000000e+00]]
kwargs:    {}
Exception: "ValueError('all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 10404000 and the array at index 8 has size 2601')"

/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
[I 2023-09-05 13:39:55.786 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:39:56.154 ServerApp] Trying to establish websocket connection to ws://localhost:8787/status/ws
[I 2023-09-05 13:39:56.156 ServerApp] Websocket connection established to ws://localhost:8787/status/ws
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
[I 2023-09-05 13:41:18.004 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:41:43.496 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 13:44:00.687 ServerApp] Kernel restarted: 38f332be-8437-4d7c-a967-2cff3436fe42
[I 2023-09-05 13:44:00.708 ServerApp] Starting buffering for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 13:44:00.724 ServerApp] Connecting to kernel 38f332be-8437-4d7c-a967-2cff3436fe42.
[I 2023-09-05 13:44:00.724 ServerApp] Restoring connection for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 13:44:33.752 ServerApp] Trying to establish websocket connection to ws://localhost:8787/status/ws
[I 2023-09-05 13:44:33.756 ServerApp] Websocket connection established to ws://localhost:8787/status/ws
[I 2023-09-05 13:45:43.804 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/home/qiahan/.conda/envs/firstEnv/lib/python3.9/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
[I 2023-09-05 13:46:48.157 ServerApp] Trying to establish websocket connection to ws://localhost:8787/workers/ws
[I 2023-09-05 13:46:48.159 ServerApp] Websocket connection established to ws://localhost:8787/workers/ws
[I 2023-09-05 13:47:44.103 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 14:08:07.889 ServerApp] Saving file at /global_data_Qianqian/Emulator/2daskParallel/0905_1year.ipynb
[I 2023-09-05 14:09:05.268 ServerApp] Starting buffering for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 14:09:05.269 ServerApp] Starting buffering for 6ebe678b-85b3-4aea-82b5-b76a6662e3ba:d6092e58-3c7b-43c2-8a85-2ab5a8240005
[I 2023-09-05 14:09:06.012 ServerApp] Connecting to kernel 38f332be-8437-4d7c-a967-2cff3436fe42.
[I 2023-09-05 14:09:06.012 ServerApp] Restoring connection for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 14:09:06.033 ServerApp] Connecting to kernel 6ebe678b-85b3-4aea-82b5-b76a6662e3ba.
[I 2023-09-05 14:09:06.033 ServerApp] Restoring connection for 6ebe678b-85b3-4aea-82b5-b76a6662e3ba:d6092e58-3c7b-43c2-8a85-2ab5a8240005
[I 2023-09-05 15:25:14.632 ServerApp] Starting buffering for 38f332be-8437-4d7c-a967-2cff3436fe42:cdbf8c64-9bf4-47e6-bfd9-9ddaa87171c0
[I 2023-09-05 15:25:14.633 ServerApp] Starting buffering for 6ebe678b-85b3-4aea-82b5-b76a6662e3ba:d6092e58-3c7b-43c2-8a85-2ab5a8240005
slurmstepd: error: *** JOB 3745990 ON fcn47 CANCELLED AT 2023-09-05T16:58:41 DUE TO TIME LIMIT ***
slurmstepd: error: container_p_join: setns failed for /slurm/3745990/.ns: Invalid argument
slurmstepd: error: container_g_join(3745990): Invalid argument

JOB STATISTICS
==============
Job ID: 3745990
Cluster: snellius
User/Group: qiahan/qiahan
State: TIMEOUT (exit code 0)
Nodes: 1
Cores per node: 32
CPU Utilized: 00:00:39
CPU Efficiency: 0.00% of 9-08:10:40 core-walltime
Job Wall-clock time: 07:00:20
Memory Utilized: 75.45 GB
Memory Efficiency: 31.44% of 240.00 GB
